# Generated by Django 6.0.5 on 2026-05-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
