# Generated by Django 6.0.5 on 2026-05-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctorprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='total_quota',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
